# Generated by Django 6.0 on 2026-01-06 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen_url',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='repartidor',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol__nombre_rol': 'Repartidores'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_asignados', to='core.usuario'),
        ),
    ]
