# Generated by Django 6.0 on 2026-01-06 10:08

import core.models.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_producto_imagen_url_producto_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='producto_nombre',
            field=models.CharField(default='Producto', help_text='Nombre del producto al momento de la venta', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detallecarrito',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_carritos', to='core.producto'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='en_pedidos', to='core.producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.utils.producto_imagen_path),
        ),
    ]
