# Generated by Django 6.0 on 2026-01-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_detallepedido_producto_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
