# Generated by Django 6.0 on 2026-01-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_categoria_alter_pedido_estado_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_PREPARACION', 'En preparación'), ('LISTO_ENTREGA', 'Listo para entrega'), ('EN_CAMINO', 'En camino'), ('ENTREGADO', 'Entregado'), ('NO_ENTREGADO', 'No entregado')], default='RECIBIDO', max_length=20),
        ),
    ]
